export const modalSettings = {
  title: "Confirmation Dialog",
  subTitle: "",
  titleWarning: false,
  hideTitle: false,
  hideSubTitle: false,
  subTitleClasses: "",
  hideHeader: false,
  hideFooter: false,
  hideCancelBtn: false,
  hideSubmitBtn: false,
  hideCloseBtn: false,
  cancelBtnText: "Close",
  cancelBtnClass: "text-primary",
  cancelBtnIcon: null,
  cancelBtnDisabled: false,
  cancelBtnIconPosition: "left",
  submitBtnIconPosition: "left",
  submitBtnText: "Submit",
  submitBtnClass: "primary",
  submitBtnClassName: "",
  submitBtnIcon: null,
  submitBtnDisabled: false,
  shouldCloseOnOverlayClick: true,
  buttonsReverse: false,
  footerAlignment: "center",
};
